### ISSUE TITLE
Examples should migrate from robotInit

### ISSUE THREAD

**Issue by sciencewhiz** [robotpy/examples#120]
### Problem description

wpilibsuite/allwpilib#6623 removed uses of robotInit in the WPILib examples and changed to using the robot constructor. This is to prepare for eventual deprecation robotInit. Python examples should be similarly updated.

### Operating System

RoboRIO

**Comment by virtuald** [comment]
I'm not sure this is a great idea at the moment. The robot constructor does a bunch of things, and I think that it depends

To support this, we would need to ensure that the robot constructor is empty or does things that doesn't matter. It looks like `wpilib._impl.start` does the important things before creating the class. If we did https://github.com/robotpy/mostrobotpy/issues/89, then we could ensure this is definitely the case.

**Comment by auscompgeek** [comment]
I thought the conclusion was RobotPy keeping robotInit was fine: https://github.com/wpilibsuite/allwpilib/pull/6623#discussion_r1636473728
