### ISSUE TITLE
CTRE

### ISSUE THREAD

**Issue by adam-mcdaniel** [robotpy/examples#13]
Ive updated the image of one of our roboRIOs to the 2018 image. Talon SRXs connected to the roboRIO by a CAN bus wont show up on the ni web configuration utility. When we use a roboRIO with the 2017 image the talons do show up. Is there a way to temporarily downgrade? Or am I doing something wrong?

**Comment by virtuald** [comment]
There's a separate thing you need to do to set that up. Refer to CTRE's documentation for more information: https://github.com/CrossTheRoadElec/Phoenix-Documentation#installing-phoenix-framework-onto-your-frc-robot

**Comment by virtuald** [comment]
Also, added this to the CTRE readme: https://github.com/robotpy/robotpy-ctre/blob/master/README.rst#ni-web-dashboard-optional
