### ISSUE TITLE
Stop using SampleRobot

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/examples#22]
It seems we have 11 examples here that still use SampleRobot:

- motor-control
- gyro
- navx
- navx-rotate-to-angle
- mecanum-drive
- navx-rotate-to-angle-arcade
- physics/src
- physics-4wheel/src
- physics-mecanum/src
- physics-spi/src
- sample/src

We can probably just remove the last one, but the others need to be updated to use TimedRobot instead.

**Comment by RustyRaptor** [comment]
agreed. This causes a lot of frustration for new programmers especially if they started with the getting-started example.

**Comment by auscompgeek** [comment]
The getting-started example doesn't use SampleRobot.

**Comment by RustyRaptor** [comment]
Yes sorry, my point is that if you start out by learning that structure of getting-started the other examples using SampleRobot can be difficult to incorporate into your code.

**Comment by auscompgeek** [comment]
This was done last year.
