### ISSUE TITLE
Update IterativeRobot examples to TimedRobot

### ISSUE THREAD

**Issue by auscompgeek** [robotpy/examples#23]
We have 10 examples still using IterativeRobot:

- pacgoat
- tank-drive
- arcade-drive
- cscore-quick-vision
- cscore-intermediate-vision
- gearsbot
- getting-started
- stateful-autonomous
- physics-camsim/src
- iterative/src

We should remove the `iterative` example and update the rest. However, `stateful-autonomous` will require robotpy/robotpy-wpilib-utilities#106 to be fixed first.

**Comment by auscompgeek** [comment]
Just gearsbot and physics-camsim left now.

**Comment by benjiboy50fonz** [comment]
@auscompgeek  Do you still need help with these last two?

**Comment by auscompgeek** [comment]
@benjiboy50fonz All yours!

**Comment by benjiboy50fonz** [comment]
@auscompgeek , merged; time to close?
