### ISSUE TITLE
Fixing examples for Robotpy 2020

### ISSUE THREAD

**Issue by CrispyBacon1999** [robotpy/examples#28]
List of examples that have been tested and work with the new versions of wpilib (that are uploaded to pypi).
- [x] `arcade-drive`
- [ ] `command-based` 

> Waiting on updated command based framework

- [ ] `cscore-intermediate` 

> Waiting on cscore update

- [ ] `cscore-quick-vision` 

> Waiting on cscore update

- [x] `game-data`

> Being added in #27 

- [x] `gearsbot`

> Waiting on updated framework

- [x] `getting-started`
- [ ] `gyro` 

> Partial support, AnalogGyro value can't be modified in simulator

- [x] `iterative`
- [x] `magicbot-simple` 
- [x] `mecanum-drive`
- [x] `motor-control`
- [x] `navx`

> Waiting for robotpy-navx update

- [x] `navx-rotate-to-angle`

> Waiting for robotpy-navx update

- [x] `navx-rotate-to-angle-arcade`

> Waiting for robotpy-navx update

- [ ] `pacgoat`

> Waiting on updated command based framework

- [x] ~`physics`~
- [x] ~`physics-4wheel`~
- [ ] ~`physics-camsim`~
- [ ] ~`physics-drive-characterization`~
- [x] ~`physics-mecanum`~
- [ ] ~`physics-pathfinder`~
- [ ] ~`physics-spi`~
- [x] `sample`

> ~~Should probably be removed as it is a demonstration of wpilib.SampleRobot which no longer exists.~~
> Removed

- [ ] `shuffleboard`

> wpilib.shuffleboard doesn't exist

- [x] `stateful-autonomous`

> Code crash when declaring autonomous modes, seems to be a generator passed in when expecting a list
```
site-packages\robotpy_ext\autonomous\stateful_autonomous.py", line 359, in __build_states
    self.MODE_NAME + "_durations", (name for _, (name, desc) in sorted_states)
TypeError: putStringArray(): incompatible function arguments. The following argument types are supported:
    1. (self: _pyntcore._ntcore.NetworkTable, key: str, value: List[str]) -> bool

Invoked with: <_pyntcore._ntcore.NetworkTable object at 0x000001C860FBC7B0>, 'Drive Backwards_durations', <generator object StatefulAutonomous.__build_states.<locals>.<genexpr> at 0x000001C860F27C48>
```

- [x] `tank-drive`
- [x] `timed`

**Comment by CrispyBacon1999** [comment]
Command based examples should work now, just need help fixing them since all of them seem to be broken in some way or another.  I'm not familiar enough with the command based framework to fix them.

**Comment by virtuald** [comment]
Tests re-enabled, so good enough for now.
