### ISSUE TITLE
Add/update new examples for 2018

### ISSUE THREAD

**Issue by virtuald** [robotpy/examples#6]
Haven't looked at what's there or not.

**Comment by auscompgeek** [comment]
I think it's mostly changing the existing examples to use the new parts of WPILib.

**Comment by virtuald** [comment]
In particular, @twinters007 can you add a TimedRobot example so we know we have test coverage for it

**Comment by twinters007** [comment]
yeah

**Comment by virtuald** [comment]
This ship has sailed.
