### ISSUE TITLE
[BUG]: Example uses conditional set rather than init

### ISSUE THREAD

**Issue by jasondaming** [robotpy/examples#79]
### Problem description

For this [example](https://github.com/robotpy/examples/blob/main/arm-simulation/robot.py#L41-L44)

The whole point of [`initDouble`](https://robotpy.readthedocs.io/projects/wpilib/en/latest/wpilib/Preferences.html#wpilib.Preferences.initDouble) is to handle this situation.  I agree they are functionally equivalent but we are using this to give examples in this [document](https://docs.wpilib.org/en/stable/docs/software/basic-programming/robot-preferences.html)

### Operating System

Windows

**Comment by virtuald** [comment]
Looks like the example was updated in 2023 with those changes.
